version: '3'

services:
  parser:
    restart: always
    build:
      context: .
    volumes:
      - ./cert:/workspace/cert
    ports:
      - 5000:8080
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      start_period: 5s
      timeout: 10s
    